export const products = [
  {
    category: 'Módulos Solares',
    title: 'Placa Solar 585W – Ronma',
    description: 'Módulo fotovoltaico de alta eficiência e durabilidade.',
    price: 'R$ 850,00',
    image: '/placa-585w.jpg',
    details: 'Placa Solar 585W da marca Ronma. Alta eficiência de conversão, excelente performance em condições de baixa luminosidade e resistência a intempéries. Ideal para projetos residenciais e comerciais.',
  },
  {
    category: 'Inversores Goodwe',
    title: 'Inversor 3.3kW – Goodwe',
    description: 'Inversor monofásico de alta performance e confiabilidade.',
    price: 'R$ 2.850,00',
    image: '/inversor-33.jpeg',
    details: 'Inversor Goodwe de 3.3kW, projetado para máxima eficiência em sistemas residenciais. Possui monitoramento inteligente integrado, design compacto e operação silenciosa.',
  },
  {
    category: 'Inversores Sofar',
    title: 'Inversor 3.3kW – Sofar',
    description: 'Inversor string eficiente, robusto e de fácil instalação.',
    price: 'R$ 2.700,00',
    image: '/inversor-33-sofar.jpeg',
    details: 'Inversor Sofar Solar de 3.3kW. Oferece alta eficiência de rastreamento MPPT, amplo range de tensão e proteção completa para o seu sistema fotovoltaico.',
  },
  {
    category: 'Inversores Goodwe',
    title: 'Inversor 5.0kW – Goodwe',
    description: 'Potência ideal para sistemas residenciais de médio porte.',
    price: 'R$ 3.900,00',
    image: '/inversor-5.jpeg',
    details: 'Inversor Goodwe de 5.0kW. Combina alta capacidade de geração com design moderno. Ideal para suprir demandas maiores de energia com total segurança e monitoramento via app.',
  },
  {
    category: 'Barramentos',
    title: 'Barramento Terra',
    description: 'Barramento de cobre para aterramento seguro do sistema.',
    price: 'R$ 45,00',
    image: '/barramento-terra.jpeg',
    details: 'Barramento de terra em cobre de alta pureza. Essencial para garantir a segurança da instalação elétrica e proteção contra surtos, seguindo as normas vigentes.',
  },
  {
    category: 'Barramentos',
    title: 'Barramento Neutro',
    description: 'Barramento de cobre para distribuição de neutro.',
    price: 'R$ 45,00',
    image: '/barramento-neutro.jpeg',
    details: 'Barramento de neutro para quadros de distribuição. Facilita a organização dos cabos e garante conexões firmes e seguras para o sistema elétrico.',
  },
  {
    category: 'Disjuntores',
    title: 'Disjuntor Monofásico C16',
    description: 'Proteção termomagnética confiável para circuitos.',
    price: 'R$ 18,00',
    image: '/disjuntor-mono-c16.jpeg',
    details: 'Disjuntor DIN monofásico curva C de 16A. Protege a instalação contra curtos-circuitos e sobrecargas, garantindo a integridade dos equipamentos solares.',
  },
  {
    category: 'Disjuntores',
    title: 'Kit com 4 Disjuntores',
    description: 'Kit completo de proteção para o quadro de distribuição.',
    price: 'R$ 65,00',
    image: '/4-disjuntores.jpeg',
    details: 'Conjunto com 4 disjuntores padrão DIN. Ideal para montagem de string boxes e quadros de proteção CA/CC em sistemas fotovoltaicos.',
  },
  {
    category: 'Conectores',
    title: 'Conector MC4 (Par)',
    description: 'Conexão segura e à prova d\'água para painéis solares.',
    price: 'R$ 12,00',
    image: '/conector-mc4.jpeg',
    details: 'Par de conectores MC4 (macho e fêmea) com proteção UV e resistência à água (IP67). Essencial para a conexão em série ou paralelo dos módulos fotovoltaicos.',
  },
  {
    category: 'Estruturas',
    title: 'Suporte Cerâmico',
    description: 'Estrutura de fixação em alumínio para telhados de cerâmica.',
    price: 'R$ 45,00',
    image: '/suporte-ceramico.jpeg',
    details: 'Gancho de fixação para telhados com telha cerâmica. Fabricado em material resistente à corrosão, garantindo a estabilidade dos painéis mesmo sob ventos fortes.',
  },
  {
    category: 'Isoladores',
    title: 'Roldana Isoladora de Porcelana',
    description: 'Isolador de alta resistência para passagem de cabos.',
    price: 'R$ 8,00',
    image: '/rold-iso-porcelana.jpeg',
    details: 'Roldana de porcelana vitrificada para isolamento e sustentação de cabos elétricos. Alta durabilidade e resistência a intempéries.',
  },
  {
    category: 'Estruturas',
    title: 'Grampo Meio',
    description: 'Fixação intermediária (mid clamp) para módulos solares.',
    price: 'R$ 6,50',
    image: '/grampo-meio.jpeg',
    details: 'Grampo intermediário em alumínio anodizado. Utilizado para fixar dois painéis adjacentes no trilho da estrutura, garantindo o espaçamento correto e segurança.',
  },
  {
    category: 'Caixas e Quadros',
    title: 'Caixa 4x2 Branca',
    description: 'Caixa de embutir padrão para instalações elétricas.',
    price: 'R$ 3,50',
    image: '/caixa-42.jpeg',
    details: 'Caixa 4x2 de embutir na cor branca. Fabricada em material termoplástico antichama, ideal para acomodar tomadas e interruptores do sistema.',
  },
  {
    category: 'Caixas e Quadros',
    title: 'Caixa Provisória',
    description: 'Caixa de sobrepor para montagem de quadro provisório.',
    price: 'R$ 25,00',
    image: '/caixa-provisoria.jpeg',
    details: 'Caixa de distribuição provisória para obras ou instalações temporárias. Robusta e com espaço adequado para disjuntores e barramentos.',
  },
  {
    category: 'Sinalização',
    title: 'Placa Geração Própria',
    description: 'Placa de advertência padrão exigida pela concessionária.',
    price: 'R$ 35,00',
    image: '/placa-propria.jpeg',
    details: 'Placa de sinalização "Cuidado - Risco de Choque Elétrico - Geração Própria". Item obrigatório para homologação do sistema junto à concessionária de energia.',
  },
  {
    category: 'Sinalização',
    title: 'Placa Geração Própria 5x8',
    description: 'Placa de advertência em tamanho reduzido (5x8cm).',
    price: 'R$ 15,00',
    image: '/placa-propria-58.jpeg',
    details: 'Placa de sinalização em formato compacto, ideal para identificação de quadros menores, string boxes e inversores.',
  }
];
